#ifndef APP_CONFIG_H
#define APP_CONFIG_H

// Таймауты состояний (мс)
#define STATE_MAIN_TIMEOUT_MS       60000
#define STATE_SHOW_TEMP_TIMEOUT_MS  10000
#define STATE_SHOW_PRESS_TIMEOUT_MS 10000
#define STATE_SHOW_HUMID_TIMEOUT_MS 10000
#define STATE_SHOW_DATE_TIMEOUT_MS  10000
#define STATE_SHOW_IR_TIMEOUT_MS    2000

#endif /* APP_CONFIG_H */
